FROM ubuntu:16.04
MAINTAINER MEAN.JS

# Install Utilities
RUN apt-get update -q
RUN apt-get install -yqq wget aptitude htop vim git traceroute dnsutils curl ssh sudo tree tcpdump nano psmisc gcc make build-essential libfreetype6 libfontconfig libkrb5-dev python2.7

# Install gem sass for grunt-contrib-sass
RUN apt-get install -y ruby
RUN gem install sass

# Install NodeJS
RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
RUN sudo apt-get install -yq nodejs

# Install MEAN.JS Prerequisites
RUN npm install --quiet -g grunt-cli gulp bower yo mocha karma-cli pm2 forever

RUN mkdir /opt/ffmedia
RUN mkdir -p /opt/ffmedia/public/lib
WORKDIR /opt/ffmedia

# Copies the local package.json file to the container
# and utilities docker container cache to not needing to rebuild
# and install node_modules/ everytime we build the docker, but only
# when the local package.json file changes.
# Install npm packages
ADD package.json /opt/ffmedia/package.json
RUN npm install --quiet

# Install bower packages
ADD bower.json /opt/ffmedia/bower.json
ADD .bowerrc /opt/ffmedia/.bowerrc
RUN bower install --quiet --allow-root --config.interactive=false

# Share local directory on the docker container
ADD . /opt/ffmedia

# Machine cleanup
RUN npm cache clean
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set development environment as default
ENV NODE_ENV development
ENV PYTHON /user/bin/python2.7

# Ports generic
EXPOSE 80:80
EXPOSE 443:443
